openapi: 3.0.1
info:
  title: Дополнительное API для взаимодействия через LTI
  version: 1.0.0
paths:
  /lmsapi/save-courses:
    post:
      tags:
        - LmsCourses
      summary: Сохранить данные о курсах LMS
      parameters:
        - name: deploymentId
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CoursesContainer'
          application/json:
            schema:
              $ref: '#/components/schemas/CoursesContainer'
          text/json:
            schema:
              $ref: '#/components/schemas/CoursesContainer'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CoursesContainer'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '404':
          description: Not Found
  /lmsapi/get-courses-to-create:
    get:
      tags:
        - LmsCourses
      summary: 'Получить курсы, которые необходимо создать в LMS'
      parameters:
        - name: deploymentId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CoursePrototype'
        '400':
          description: Bad Request
        '404':
          description: Not Found
  /lmsapi/getlinks:
    get:
      tags:
        - LmsLink
      summary: Получить связи РМУПов с курсами LMS
      description: 'Метод использует контракты, описанные в LTI Launch'
      parameters:
        - name: deploymentId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinksContainer'
        '400':
          description: Bad Request
        '404':
          description: Not Found
components:
  schemas:
    Course:
      type: object
      properties:
        id:
          type: string
          description: ИД курса в Инструменте LMS
        lmsIdNumber:
          type: string
          description: 'ИД в Платформе LMS (для курсов, созданных по данным платформы)'
          nullable: true
        name:
          type: string
          description: Название
        customLtiProperties:
          type: string
          description: Пользовательские свойства LTI
        modules:
          type: array
          items:
            $ref: '#/components/schemas/Module'
          description: Состав (элементы) курса
      additionalProperties: false
      description: Курс LMS
    CoursePrototype:
      type: object
      properties:
        id:
          type: string
          description: ИД курса в Платформе LTI
        name:
          type: string
          description: Название
        shortName:
          type: string
          description: Краткое название
        summary:
          type: string
          description: Описание
        sections:
          type: array
          items:
            $ref: '#/components/schemas/SectionPrototype'
          description: Состав курса
      additionalProperties: false
      description: Курс для создания в Инструменте LTI
    CoursesContainer:
      type: object
      properties:
        courses:
          type: array
          items:
            $ref: '#/components/schemas/Course'
          description: Курсы
        moduleTypes:
          type: array
          items:
            $ref: '#/components/schemas/ModuleType'
          description: Типы элементов
      additionalProperties: false
      description: Информация о курсах в Инструменте LTI
    LinksContainer:
      type: object
      properties:
        links:
          type: array
          items:
            type: object
            additionalProperties: { }
            description: https://purl.imsglobal.org/spec/lti/v1p3/schema/json/LtiResourceLinkRequest.json
          description: Связи
      additionalProperties: false
      description: Связи курсов Платформы с курсами Инструмента LTI
    Module:
      type: object
      properties:
        id:
          type: string
          description: ИД элемента в Инструменте LTI
        lmsIdNumber:
          type: string
          description: 'ИД элемента в Платформе LTI (для элементов, созданных по данным платформы)'
          nullable: true
        name:
          type: string
          description: Название
        customLtiProperties:
          type: string
          description: Пользовательские свойства LTI
        moduleTypeId:
          type: string
          description: Тип элемента
      additionalProperties: false
      description: Элемент курса LMS
    ModulePrototype:
      type: object
      properties:
        id:
          type: string
          description: ИД элемента в Платформе LTI
        name:
          type: string
          description: Название
        moduleTypeId:
          type: string
          description: Тип элемента
      additionalProperties: false
      description: Элемент курса LMS
    ModuleType:
      type: object
      properties:
        id:
          type: string
          description: ИД
        name:
          type: string
          description: Имя
        canCreate:
          type: boolean
          description: Можно ли создавать курсы с таким элементом? LMS поддерживает создание не всех типов элементов
      additionalProperties: false
      description: Тип элемента LMS
    SectionPrototype:
      type: object
      properties:
        name:
          type: string
          description: Название
        modules:
          type: array
          items:
            $ref: '#/components/schemas/ModulePrototype'
          description: Элементы курса
      additionalProperties: false
      description: Секция курса LMS